baseURL = "https://derk1998.github.io/bees/"
languageCode = "en-us"
title = "Minor Smart Industry: Bees project"
theme = "terrassa"

[params.posts]
    showDate = true
    dateFormat = "Monday, Jan, 2006"
